## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
notifications:
  email: false
git:
  depth: 99999999
before-install:
  - sudo apt-get install curl
script:
  - julia -e 'using Pkg; add(PackageSpec(url=pwd()));'
  - julia -e 'using Pkg; test("MathOptInterfaceMosek")'

